export const data = {
    categories: [
        {
          name: "Car",
          keywords: [
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
            "BMW",
            "Mercedes",
            "Ferrari",
          ],
        },
        {
          name: "Fruit",
          keywords: ["Apple", "Orange", "Starberry"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Country",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
        {
          name: "Countryyyy",
          keywords: ["Brazil", "Portugal", "Germany"],
        },
      ]
};

